In [8]:
from models.lag_ml_model import get_data,preprocess_data,classifier_models,train_model,grid_optimize_model,random_optimize_model,get_param_grids
from backtesting import Backtest,Strategy
import pandas as pd
import os
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from main import backtest_loop,backtest,risk_backtest_loop,risk_backtest,scaling_function,normal_model,random_model,grid_model

In [9]:
path = r"C:\Users\sachi\Documents\Researchcode\Conferance_Data\merged_data_META_from_2015-01-01_to_2025-03-01.csv"

df = get_data(path,ind=True)
X_train,X_test,y_train,y_test = preprocess_data(df,max_lag=5)
X_train_scaled,X_test_scaled = scaling_function(X_train,X_test)
#No Optimation Model
results,y_pred_dict = normal_model(X_train_scaled,X_test_scaled,y_train,y_test)
normal_df,bt_collection = backtest_loop(y_pred_dict,X_test)
risk_df,bt_collection = risk_backtest_loop(y_pred_dict,X_test)
actual,_ = backtest(y_test,X_test)
actual['Model'] = 'Actual'
actual = pd.DataFrame(actual).T
normal_merge = pd.merge(results,normal_df, how='inner')
normal_merge = pd.concat([normal_merge,actual],axis=0)
risk_merge = pd.merge(results,risk_df, how='inner')
risk_merge = pd.concat([risk_merge,actual],axis=0)
normal_merge = pd.merge(normal_merge,risk_merge, on='Model')



Logistic Regression Performance:
Accuracy: 0.8079
Confusion Matrix:
[[173  79]
 [ 66 437]]
              precision    recall  f1-score   support

           0       0.72      0.69      0.70       252
           1       0.85      0.87      0.86       503

    accuracy                           0.81       755
   macro avg       0.79      0.78      0.78       755
weighted avg       0.81      0.81      0.81       755


Random Forest Performance:
Accuracy: 0.8437
Confusion Matrix:
[[200  52]
 [ 66 437]]
              precision    recall  f1-score   support

           0       0.75      0.79      0.77       252
           1       0.89      0.87      0.88       503

    accuracy                           0.84       755
   macro avg       0.82      0.83      0.83       755
weighted avg       0.85      0.84      0.84       755


XGBoost Performance:
Accuracy: 0.8371
Confusion Matrix:
[[186  66]
 [ 57 446]]
              precision    recall  f1-score   support

           0       0.77      0.74

c:\Users\sachi\Documents\Researchcode\research\lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(



MLP Performance:
Accuracy: 0.7894
Confusion Matrix:
[[193  59]
 [100 403]]
              precision    recall  f1-score   support

           0       0.66      0.77      0.71       252
           1       0.87      0.80      0.84       503

    accuracy                           0.79       755
   macro avg       0.77      0.78      0.77       755
weighted avg       0.80      0.79      0.79       755

[LightGBM] [Info] Number of positive: 1092, number of negative: 669
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000931 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 6630
[LightGBM] [Info] Number of data points in the train set: 1761, number of used features: 26
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.620102 -> initscore=0.489982
[LightGBM] [Info] Start training from score 0.489982
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further sp

Backtesting for Random Forest


Backtesting for XGBoost


Backtesting for SVM


Backtesting for Naive Bayes


Backtesting for Gradient Boosting


Backtesting for K-Nearest Neighbors


Backtesting for Decision Tree


Backtesting for AdaBoost


Backtesting for SGD Classifier


Backtesting for MLP


Backtesting for LGBMClassifier


Backtesting for Logistic Regression


Backtesting for Random Forest


Backtesting for XGBoost


Backtesting for SVM


Backtesting for Naive Bayes


Backtesting for Gradient Boosting


Backtesting for K-Nearest Neighbors


Backtesting for Decision Tree


Backtesting for AdaBoost


Backtesting for SGD Classifier


Backtesting for MLP


Backtesting for LGBMClassifier


In [20]:
pd.set_option('display.max_columns',None)

In [21]:
normal_merge[normal_merge['Return [%]_x'] > normal_merge['Buy & Hold Return [%]_x']]

Model  Accuracy_x      Confusion Matrix_x  \
0   Logistic Regression    0.807947  [[173, 79], [66, 437]]   
1         Random Forest    0.843709  [[200, 52], [66, 437]]   
2               XGBoost    0.837086  [[186, 66], [57, 446]]   
3                   SVM    0.801325  [[171, 81], [69, 434]]   
6   K-Nearest Neighbors    0.810596  [[187, 65], [78, 425]]   
7         Decision Tree    0.831788  [[201, 51], [76, 427]]   
8              AdaBoost    0.845033  [[195, 57], [60, 443]]   
9        SGD Classifier    0.789404  [[162, 90], [69, 434]]   
12               Actual         NaN                     NaN   

                Start_x                End_x          Duration_x  \
0   2022-02-24 00:00:00  2025-02-27 00:00:00  1099 days 00:00:00   
1   2022-02-24 00:00:00  2025-02-27 00:00:00  1099 days 00:00:00   
2   2022-02-24 00:00:00  2025-02-27 00:00:00  1099 days 00:00:00   
3   2022-02-24 00:00:00  2025-02-27 00:00:00  1099 days 00:00:00   
6   2022-02-24 00:00:00  2025-02-27 00:00:00  1099 days 00:00:00   
7   2022-02-24 00:00:00  2025-02-27 00:00:00  1099 days 00:00:00   
8   2022-02-24 00:00:00  2025-02-27 00:00:00  1099 days 00:00:00   
9   2022-02-24 00:00:00  2025-02-27 00:00:00  1099 days 00:00:00   
12  2022-02-24 00:00:00  2025-02-27 00:00:00  1099 days 00:00:00   

   Exposure Time [%]_x Equity Final [$]_x Equity Peak [$]_x Return [%]_x  \
0            51.523179       43530.097794       48706.47731   335.300978   
1            67.682119       34913.812592      38590.213226   249.138126   
2            69.668874       33853.874069      37781.891953   238.538741   
3            70.596026       45449.768349      49028.286415   354.497683   
6            68.476821       35100.236916       38776.63755   251.002369   
7            67.549669       34882.232452      38558.633087   248.822325   
8             67.94702       35682.474609      39841.552368   256.824746   
9             51.92053       33245.239456       37166.73909   232.452395   
12            68.07947       45313.610352       48639.34729   353.136104   

   Buy & Hold Return [%]_x Return (Ann.) [%]_x Volatility (Ann.) [%]_x  \
0               217.071277           63.384896               52.244859   
1               217.071277           51.788485               48.073421   
2               217.071277           50.234594               48.370987   
3               217.071277           65.755339               52.688936   
6               217.071277           52.058524               48.211876   
7               217.071277           51.742645               48.059113   
8               217.071277           52.895803                49.18605   
9               217.071277           49.327628               48.228992   
12              217.071277           65.589431               55.476227   

   CAGR [%]_x Sharpe Ratio_x Sortino Ratio_x Calmar Ratio_x Alpha [%]_x  \
0   40.111589       1.213227        4.048465       2.668824  240.702131   
1   33.201443       1.077279        3.209624       2.017316  155.050089   
2    32.26315       1.038527        3.043399         1.7084  141.511214   
3   41.504938       1.247991        4.290993       2.741442  260.471632   
6   33.364195       1.079786        3.278896        1.71319  155.981489   
7   33.173807       1.076646        3.221048       2.465088  155.820728   
8   33.868246       1.075423        3.218659       2.391612  159.992845   
9    31.71409        1.02278        2.947457       1.941232   133.81675   
12  41.407621       1.182298        3.748676       2.814679  245.584411   

      Beta_x Max. Drawdown [%]_x Avg. Drawdown [%]_x Max. Drawdown Duration_x  \
0   0.435796          -23.750119           -4.076892        298 days 00:00:00   
1   0.433443          -25.671981           -4.565828        304 days 00:00:00   
2   0.446985          -29.404465           -4.727164        304 days 00:00:00   
3   0.433158          -23.985676           -3.967596        298 days 00:00:00   
6    0.43774          -30.386901           -4.23

In [10]:
y_test_aligned = pd.Series(y_test, index=X_test.index, name='target')
merged_data = pd.concat([X_test, y_test_aligned], axis=1)

In [11]:
import plotly.graph_objects as go

buy_signals = merged_data[merged_data['target'] == 1]
sell_signals = merged_data[merged_data['target'] == 0]

fig = go.Figure(data=[go.Candlestick(
    x=merged_data.index,  # Use the index as the x-axis (Date)
    open=merged_data['Open'],  # Opening prices
    high=merged_data['High'],  # High prices
    low=merged_data['Low'],  # Low prices
    close=merged_data['Close'],  # Closing prices
    increasing_line_color='green',  # Color for increasing candles
    decreasing_line_color='red'  # Color for decreasing candles
)])

# Add scatter points for buy signals
fig.add_trace(go.Scatter(
    x=buy_signals.index,  # Use the index of buy signals
    y=buy_signals['Close'],  # Plot buy signals at the Close price
    mode='markers',  # Use markers to represent the signals
    name='Buy Signal',  # Legend name for buy signals
    marker=dict(
        size=10,  # Marker size
        color='green',  # Marker color for buy signals
        symbol='triangle-up'  # Marker shape for buy signals
    )
))

# Add scatter points for sell signals
fig.add_trace(go.Scatter(
    x=sell_signals.index,  # Use the index of sell signals
    y=sell_signals['Close'],  # Plot sell signals at the Close price
    mode='markers',  # Use markers to represent the signals
    name='Sell Signal',  # Legend name for sell signals
    marker=dict(
        size=10,  # Marker size
        color='red',  # Marker color for sell signals
        symbol='triangle-down'  # Marker shape for sell signals
    )
))

# Add title and labels
fig.update_layout(
    title='Candlestick Chart with Buy and Sell Signals',
    xaxis_title='Date',
    yaxis_title='Price',
    xaxis_rangeslider_visible=False  # Hide the range slider (optional)
)

# Show the chart
fig.show()


In [17]:
import plotly.graph_objects as go
import pandas as pd

# Assuming merged_data is your DataFrame
# Ensure the required columns exist in merged_data
# Columns: 'Open', 'High', 'Low', 'Close', 'target'

# Identify signal changes
merged_data['signal_change'] = merged_data['target'].diff().fillna(0)  # Detect changes in the target column

# Filter rows where signal changes occur
signal_changes = merged_data[merged_data['signal_change'] != 0]

# Separate buy and sell signals
buy_signals = signal_changes[signal_changes['target'] == 1]  # Buy signals (target changes to 1)
sell_signals = signal_changes[signal_changes['target'] == 0]  # Sell signals (target changes to 0)

# Create the candlestick chart
fig = go.Figure(data=[go.Candlestick(
    x=merged_data.index,  # Use the index as the x-axis (Date)
    open=merged_data['Open'],  # Opening prices
    high=merged_data['High'],  # High prices
    low=merged_data['Low'],  # Low prices
    close=merged_data['Close'],  # Closing prices
    increasing_line_color='lime',  # Bright green for increasing candles
    decreasing_line_color='red',  # Bright red for decreasing candles
    increasing_fillcolor='lime',  # Fill color for increasing candles
    decreasing_fillcolor='red',  # Fill color for decreasing candles
    line_width=1.5  # Make the candles thicker
)])

# Add scatter points for buy signals
fig.add_trace(go.Scatter(
    x=buy_signals.index,  # Use the index of buy signals
    y=buy_signals['Open'],  # Plot buy signals at the Open price
    mode='markers',  # Use markers to represent the signals
    name='Buy Signal',  # Legend name for buy signals
    marker=dict(
        size=12,  # Larger marker size
        color='yellow',  # Bright green for buy signals
        symbol='triangle-up'  # Marker shape for buy signals
    )
))

# Add scatter points for sell signals
fig.add_trace(go.Scatter(
    x=sell_signals.index,  # Use the index of sell signals
    y=sell_signals['Open'],  # Plot sell signals at the Open price
    mode='markers',  # Use markers to represent the signals
    name='Sell Signal',  # Legend name for sell signals
    marker=dict(
        size=12,  # Larger marker size
        color='yellow',  # Bright red for sell signals
        symbol='triangle-down'  # Marker shape for sell signals
    )
))

# Customize the layout for better visuals
fig.update_layout(
    title='Candlestick Chart with Buy and Sell Signal Changes',
    xaxis_title='Date',
    yaxis_title='Price',
    xaxis_rangeslider_visible=False,  # Hide the range slider (optional)
    plot_bgcolor='black',  # Set the background color to black
    paper_bgcolor='black',  # Set the outer background color to black
    font=dict(color='white'),  # Set font color to white for better contrast
    xaxis=dict(showgrid=False),  # Remove gridlines on the x-axis
    yaxis=dict(showgrid=False)  # Remove gridlines on the y-axis
)

# Show the chart
fig.show()


In [23]:
y_pred_dict['Logistic Regression']

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,

In [25]:

y_pred_aligned = pd.Series(y_pred_dict['Logistic Regression'], index=X_test.index, name='target')
merged_data = pd.concat([X_test, y_pred_aligned], axis=1)

In [29]:
import plotly.graph_objects as go
import pandas as pd

# Assuming merged_data is your DataFrame
# Ensure the required columns exist in merged_data
# Columns: 'Open', 'High', 'Low', 'Close', 'target'

# Identify signal changes
merged_data['signal_change'] = merged_data['target'].diff().fillna(0)  # Detect changes in the target column

# Filter rows where signal changes occur
signal_changes = merged_data[merged_data['signal_change'] != 0]

# Separate buy and sell signals
buy_signals = signal_changes[signal_changes['target'] == 1]  # Buy signals (target changes to 1)
sell_signals = signal_changes[signal_changes['target'] == 0]  # Sell signals (target changes to 0)

# Create the candlestick chart
fig = go.Figure(data=[go.Candlestick(
    x=merged_data.index,  # Use the index as the x-axis (Date)
    open=merged_data['Open'],  # Opening prices
    high=merged_data['High'],  # High prices
    low=merged_data['Low'],  # Low prices
    close=merged_data['Close'],  # Closing prices
    increasing_line_color='lime',  # Bright green for increasing candles
    decreasing_line_color='red',  # Bright red for decreasing candles
    increasing_fillcolor='lime',  # Fill color for increasing candles
    decreasing_fillcolor='red',  # Fill color for decreasing candles
    line_width=1.5  # Make the candles thicker
)])

# Add scatter points for buy signals
fig.add_trace(go.Scatter(
    x=buy_signals.index,  # Use the index of buy signals
    y=buy_signals['Open'],  # Plot buy signals at the Open price
    mode='markers',  # Use markers to represent the signals
    name='Buy Signal',  # Legend name for buy signals
    marker=dict(
        size=12,  # Larger marker size
        color='yellow',  # Bright green for buy signals
        symbol='triangle-up'  # Marker shape for buy signals
    )
))

# Add scatter points for sell signals
fig.add_trace(go.Scatter(
    x=sell_signals.index,  # Use the index of sell signals
    y=sell_signals['Open'],  # Plot sell signals at the Open price
    mode='markers',  # Use markers to represent the signals
    name='Sell Signal',  # Legend name for sell signals
    marker=dict(
        size=12,  # Larger marker size
        color='yellow',  # Bright red for sell signals
        symbol='triangle-down'  # Marker shape for sell signals
    )
))

# Customize the layout for better visuals
fig.update_layout(
    title='Candlestick Chart with Buy and Sell Signal Changes(Logistic Regression for 0 day lag)',
    xaxis_title='Date',
    yaxis_title='Price',
    xaxis_rangeslider_visible=False,  # Hide the range slider (optional)
    plot_bgcolor='black',  # Set the background color to black
    paper_bgcolor='black',  # Set the outer background color to black
    font=dict(color='white'),  # Set font color to white for better contrast
    xaxis=dict(showgrid=False),  # Remove gridlines on the x-axis
    yaxis=dict(showgrid=False)  # Remove gridlines on the y-axis
)

# Show the chart
fig.show()


In [13]:
import plotly.graph_objects as go
import pandas as pd

# Assuming merged_data is your DataFrame
# Ensure the required columns exist in merged_data
# Columns: 'Open', 'High', 'Low', 'Close', 'target'

# Identify signal changes
merged_data['signal_change'] = merged_data['target'].diff().fillna(0)  # Detect changes in the target column

# Filter rows where signal changes occur
signal_changes = merged_data[merged_data['signal_change'] != 0]

# Separate buy and sell signals
buy_signals = signal_changes[signal_changes['target'] == 1]  # Buy signals (target changes to 1)
sell_signals = signal_changes[signal_changes['target'] == 0]  # Sell signals (target changes to 0)

# Create the candlestick chart
fig = go.Figure(data=[go.Candlestick(
    x=merged_data.index,  # Use the index as the x-axis (Date)
    open=merged_data['Open'],  # Opening prices
    high=merged_data['High'],  # High prices
    low=merged_data['Low'],  # Low prices
    close=merged_data['Close'],  # Closing prices
    increasing_line_color='lime',  # Bright green for increasing candles
    decreasing_line_color='red',  # Bright red for decreasing candles
    increasing_fillcolor='lime',  # Fill color for increasing candles
    decreasing_fillcolor='red',  # Fill color for decreasing candles
    line_width=1.5  # Make the candles thicker
)])

# Add scatter points for buy signals
fig.add_trace(go.Scatter(
    x=buy_signals.index,  # Use the index of buy signals
    y=buy_signals['High'] + (buy_signals['High'] * 0.02),  # Plot buy signals slightly above the High price
    mode='markers',  # Use markers to represent the signals
    name='Buy Signal',  # Legend name for buy signals
    marker=dict(
        size=12,  # Larger marker size
        color='lime',  # Bright green for buy signals
        symbol='triangle-up'  # Marker shape for buy signals
    )
))

# Add scatter points for sell signals
fig.add_trace(go.Scatter(
    x=sell_signals.index,  # Use the index of sell signals
    y=sell_signals['Low'] - (sell_signals['Low'] * 0.02),  # Plot sell signals slightly below the Low price
    mode='markers',  # Use markers to represent the signals
    name='Sell Signal',  # Legend name for sell signals
    marker=dict(
        size=12,  # Larger marker size
        color='red',  # Bright red for sell signals
        symbol='triangle-down'  # Marker shape for sell signals
    )
))

# Customize the layout for better visuals
fig.update_layout(
    title='Candlestick Chart with Buy and Sell Signal Changes',
    xaxis_title='Date',
    yaxis_title='Price',
    xaxis_rangeslider_visible=False,  # Hide the range slider (optional)
    plot_bgcolor='black',  # Set the background color to black
    paper_bgcolor='black',  # Set the outer background color to black
    font=dict(color='white'),  # Set font color to white for better contrast
    xaxis=dict(showgrid=False),  # Remove gridlines on the x-axis
    yaxis=dict(showgrid=False)  # Remove gridlines on the y-axis
)

# Show the chart
fig.show()


In [14]:
df.columns

Index(['Date', 'Close', 'High', 'Low', 'Open', 'Volume', 'sentiment_score',
       'shifted_direction', 'RSI_14', 'MACD_12_26_9', 'MACDh_12_26_9',
       'MACDs_12_26_9', 'ADX_14', 'DMP_14', 'DMN_14', 'EMA_20', 'BBL_20_2.0',
       'BBU_20_2.0', 'BBB_20_2.0', 'BBP_20_2.0', 'OBV', 'STOCHk_14_3_3',
       'STOCHd_14_3_3'],
      dtype='object')