In [144]:
from models.lag_ml_model import scaling_function,preprocess_data,classifier_models,train_model,grid_optimize_model,random_optimize_model,get_param_grids,get_data
from backtesting import Backtest,Strategy
import pandas as pd
def backtest(y_pred, X_test):
    def get_signal():
        print(type(y_pred))
        return y_pred
    class MyStrategy(Strategy):
        def init(self):
            self.signal = self.I(get_signal)
        def next(self):
            print(f"Signal: {self.signal[-1]}, Position: {self.position}")
            if self.signal[-1] == 1:
                if not self.position:
                    print("Executing Buy Order")
                    self.buy()
            elif self.signal[-1] == 0:
                if self.position:
                    print("Closing Position")
                    self.position.close()

    bt = Backtest(X_test,MyStrategy,cash=10000,commission=0.0002,exclusive_orders=True)
    stats = bt.run()
    return stats,bt

# No optimization

In [ ]:
df = get_data(path=r'C:\Users\sachi\Documents\Researchcode\sentiment\merged_data_AAPL_from_2015-01-01_to_2025-03-01.csv')
X_train,X_test,y_train,y_test = preprocess_data(df)
X_train_scaled,X_test_scaled = scaling_function(X_train,X_test)
print(X_train_scaled.shape,X_test_scaled.shape,y_train.shape,y_test.shape)
classifier = classifier_models()
results,y_pred_dict = train_model(classifiers=classifier, X_train_scaled=X_train_scaled, X_test_scaled=X_test_scaled,y_train=y_train,y_test=y_test)





(1745, 66) (749, 66) (1745,) (749,)

Logistic Regression Performance:
Accuracy: 0.8879
Confusion Matrix:
[[310  45]
 [ 39 355]]
              precision    recall  f1-score   support

           0       0.89      0.87      0.88       355
           1       0.89      0.90      0.89       394

    accuracy                           0.89       749
   macro avg       0.89      0.89      0.89       749
weighted avg       0.89      0.89      0.89       749


Random Forest Performance:
Accuracy: 0.6075
Confusion Matrix:
[[280  75]
 [219 175]]
              precision    recall  f1-score   support

           0       0.56      0.79      0.66       355
           1       0.70      0.44      0.54       394

    accuracy                           0.61       749
   macro avg       0.63      0.62      0.60       749
weighted avg       0.63      0.61      0.60       749


XGBoost Performance:
Accuracy: 0.5394
Confusion Matrix:
[[ 10 345]
 [  0 394]]
              precision    recall  f1-score   suppor

c:\Users\sachi\Documents\Researchcode\research\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\sachi\Documents\Researchcode\research\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\sachi\Documents\Researchcode\research\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capita


Gradient Boosting Performance:
Accuracy: 0.6088
Confusion Matrix:
[[249 106]
 [187 207]]
              precision    recall  f1-score   support

           0       0.57      0.70      0.63       355
           1       0.66      0.53      0.59       394

    accuracy                           0.61       749
   macro avg       0.62      0.61      0.61       749
weighted avg       0.62      0.61      0.61       749


K-Nearest Neighbors Performance:
Accuracy: 0.6649
Confusion Matrix:
[[217 138]
 [113 281]]
              precision    recall  f1-score   support

           0       0.66      0.61      0.63       355
           1       0.67      0.71      0.69       394

    accuracy                           0.66       749
   macro avg       0.66      0.66      0.66       749
weighted avg       0.66      0.66      0.66       749


Decision Tree Performance:
Accuracy: 0.5794
Confusion Matrix:
[[ 59 296]
 [ 19 375]]
              precision    recall  f1-score   support

           0       0.76

c:\Users\sachi\Documents\Researchcode\research\lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(


In [146]:
results

Model  Accuracy          Confusion Matrix
0   Logistic Regression  0.887850    [[310, 45], [39, 355]]
1         Random Forest  0.607477   [[280, 75], [219, 175]]
2               XGBoost  0.539386     [[10, 345], [0, 394]]
3                   SVM  0.886515    [[319, 36], [49, 345]]
4           Naive Bayes  0.526035      [[0, 355], [0, 394]]
5     Gradient Boosting  0.608812  [[249, 106], [187, 207]]
6   K-Nearest Neighbors  0.664887  [[217, 138], [113, 281]]
7         Decision Tree  0.579439    [[59, 296], [19, 375]]
8              AdaBoost  0.527370      [[2, 353], [1, 393]]
9        SGD Classifier  0.809079    [[350, 5], [138, 256]]
10                  MLP  0.833111    [[257, 98], [27, 367]]
11       LGBMClassifier  0.636849     [[87, 268], [4, 390]]

In [147]:
stats_l=[]
bt_collection = {}
for name,y_pred in y_pred_dict.items():
    print(f"Backtesting for {name}")
    stats,bt = backtest(y_pred,X_test)
    bt_collection[name] = bt
    stats['Algorithm'] = name
    stats_l.append(stats)

normal_df = pd.DataFrame(stats_l)

Backtesting for Logistic Regression
<class 'numpy.ndarray'>


Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 1, Position: <Position: 0 (0 trades)>
Executing Buy Order
Signal: 1, Position: <Position: 58 (1 trades)>
Signal: 1, Position: <Position: 58 (1 trades)>
Signal: 1, Position: <Position: 58 (1 trades)>
Signal: 1, Position: <Position: 58 (1 trades)>
Signal: 1, Position: <Position: 58 (1 trades)>
Signal: 1, Position: <Position: 58 (1 trades)>
Signal: 1, Position: <Position: 58 (1 trades)>
Signal: 1, Position: <Position: 58 (1 trades)>
Signal

Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 1, Position: <Position: 0 (0 trades)>
Executing Buy Order
Signal: 0, Position: <Position: 57 (1 trades)>
Closing Position
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 1, Position: <Position: 0 (0 trades)>
Executing Buy Order
Signal: 1, Position: <Position: 56 (1 trades)>
Signal: 1, Position: 

Signal: 1, Position: <Position: 0 (0 trades)>
Executing Buy Order
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 tra

Backtesting for SVM
<class 'numpy.ndarray'>


Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 1, Position: <Position: 0 (0 trades)>
Executing Buy Order
Signal: 1, Position: <Position: 58 (1 trades)>
Signal: 1, Position: <Position: 58 (1 trades)>
Signal: 1, Position: <Position: 58 (1 trades)>
Signal: 1, Position: <Position: 58 (1 trades)>
Signal: 1, Position: <Position: 58 (1 trades)>
Signal: 1, Position: <Position: 58 (1 trades)>
Signal: 1, Position: <Position: 58 (1 trades)>
Signal: 1, Position: <Position: 58 (1 trades)>
Signal

Signal: 1, Position: <Position: 0 (0 trades)>
Executing Buy Order
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 tra

Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 1, Position: <Position: 0 (0 trades)>
Executing Buy Order
Signal: 1, Position: <Position: 59 (1 trades)>
Signal: 1, Position: <Position: 59 (1 trades)>
Signal: 1, Position: <Position: 59 (1 trades)>
Signal: 1, Position: <Position: 59 (1 trades)>
Signal: 1, Position: <Position: 59 (1 trades)>
Signal: 1, Position: <Position: 59 (1 trades)>
Signal: 1, Position: <Position: 59 (1 trades)>
Signal: 1, Position: <Position: 59 (1 trades)>
Signal: 1, Position: <Position: 59 (1 trades)>
Signa

Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 1, Position: <Position: 0 (0 trades)>
Executing Buy Order
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 0, Position: <Position: 62 (1 trades)>
Closing Position
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 1, Position: <Position: 0 (0 trades)>
Executing Buy Order
Signal: 0, Position: <Position: 57 (1 trades)>
Closing Position
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 1, Position: <Position: 0 (0 trades)>
Executing Buy Order
Signal: 0, Position: <Position: 54 (1 trades)>
Closing Position
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 1, 

Signal: 1, Position: <Position: 0 (0 trades)>
Executing Buy Order
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 tra

Signal: 1, Position: <Position: 0 (0 trades)>
Executing Buy Order
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 tra

Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 1, Position: <Position: 0 (0 trades)>
Executing Buy Order
Signal: 1, Position: <Position: 56 (1 trades)>
Signal: 1, Position: <Position: 56 (1 trades)>
Signal: 1, Position: <Position: 56 (1 trades)>
Signal: 1, Position: <Position: 56 (1 trades)>
Signal: 1, Position: <Position: 56 (1 trades)>
Signal: 1

Backtesting for MLP
<class 'numpy.ndarray'>


Backtest.run:   0%|          | 0/748 [00:00<?, ?it/s]

Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 1, Position: <Position: 0 (0 trades)>
Executing Buy Order
Signal: 1, Position: <Position: 58 (1 trades)>
Signal: 1, Position: <Position: 58 (1 trades)>
Signal: 1, Position: <Position: 58 (1 trades)>
Signal: 1, Position: <Position: 58 (1 trades)>
Signal: 1, Position: <Position: 58 (1 trades)>
Signal: 1, Position: <Position: 58 (1 trades)>
Signal: 1, Position: <Position: 58 (1 trades)>
Signal: 1, Position: <Position: 58 (1 trades)>
Signal

Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 1, Position: <Position: 0 (0 trades)>
Executing Buy Order
Signal: 1, Position: <Position: 53 (1 trades)>
Signal: 1, Position: <Position: 53 (1 trades)>
Signal: 1, Position: <Position: 53 (1 trades)>
Signal: 1, Position: <Position: 53 (1 trades)>
Signal: 1, Position: <Position: 53 (1 trades)>
Signal: 1, Position: <Position: 53 (1 trades)>
Signal: 1, Position: <Position: 53 (1 trades)>
Signal: 1, Position: <Position: 53 (1 trades)>
Signal: 1, Position: <Position: 53 (1 trades)>
Signal: 1, Position: <Position: 53 (1 trades)>
Signal: 1, Position: <Position: 53 (1 trades)>
Signal: 1, Position: <Position: 53 (1 trades)>
Signal: 1, Position: <Position: 53 (1 trades)>
Signal: 1, Position: <Position: 53 (1 trades)>
Signal: 1, Position: <Position: 53 (1 trades)>
Signal: 1, Position: <Position: 53 (1 trades)

Signal: 1, Position: <Position: 0 (0 trades)>
Executing Buy Order
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 0, Position: <Position: 62 (1 trades)>
Closing Position
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 1, Position: <Position: 0 (0 trades)>
Executing Buy Order
Signal: 1, Position: <Position: 66 (1 trades)>
Signal: 1, Position: <Position: 66 (1 trades)>
Signal: 1, Position: <Position: 66 (1 trades)>
Signal: 1, Position: <Position: 66 (1 trades)>
Signal: 1, Position: <Position: 66 (1 trades)>
Signal: 1, Position: <Position: 66 (1 trades)>
Signal: 1, Position: <Position: 66 (1 trades)>
Signal: 1, Position: <Position: 66 (1 trades)>
Signal: 1, Position: <Position: 66 (1 trades)>
Signal: 1, Position: <Position: 66 (1 trades)>
Signal: 1, Position: <Position: 66 (1 trades)>
Signal: 1, Position: <Position: 66 (1 trades)>
Signal: 1, Position: <Position: 66 (1 trades)>
Signal: 1, Position: <Position: 66 (1 trades)>
Signal: 1, Position: <Position: 66 (1 trades)>
Signal

In [148]:
normal_df

Start        End  Duration  Exposure Time [%]  Equity Final [$]  \
0  2022-03-04 2025-02-27 1091 days          55.006676       9894.180998   
1  2022-03-04 2025-02-27 1091 days          35.380507      10824.763922   
2  2022-03-04 2025-02-27 1091 days          27.636849      14093.888193   
3  2022-03-04 2025-02-27 1091 days          52.336449      11979.267743   
4  2022-03-04 2025-02-27 1091 days           0.000000      14863.790367   
5  2022-03-04 2025-02-27 1091 days          45.794393      11714.022585   
6  2022-03-04 2025-02-27 1091 days          64.886515      12404.808667   
7  2022-03-04 2025-02-27 1091 days          25.367156      10445.580834   
8  2022-03-04 2025-02-27 1091 days          22.029372      14256.701409   
9  2022-03-04 2025-02-27 1091 days          35.781041      14014.379815   
10 2022-03-04 2025-02-27 1091 days          62.616822      12229.113679   
11 2022-03-04 2025-02-27 1091 days          61.682243      14097.946560   

    Equity Peak [$]  Commissions [$]  Return [%]  Buy & Hold Return [%]  \
0      12249.298394        87.269280   -1.058190              45.431149   
1      10824.763922        51.845438    8.247639              45.431149   
2      15375.367365         9.941782   40.938882              45.431149   
3      13701.264070        90.707834   19.792677              45.431149   
4      16210.429497              NaN   48.637904              45.431149   
5      12727.615831       127.656340   17.140226              45.431149   
6      13154.358600       293.847148   24.048087              45.431149   
7      11401.260217        59.401896    4.455808              45.431149   
8      15559.900567        11.097268   42.567014              45.431149   
9      16371.331645        62.688480   40.143798              45.431149   
10     13494.163543        69.098790   22.291137              45.431149   
11     15379.425732        77.401360   40.979466              45.431149   

    Return (Ann.) [%]  ...  Max. Trade Duration  Avg. Trade Duration  \
0           -0.357284  ...             145 days              26 days   
1            2.702268  ...             185 days              25 days   
2           12.238334  ...             190 days              98 days   
3            6.264390  ...             144 days              26 days   
4           14.264876  ...                  NaT                  NaT   
5            5.466870  ...             175 days              16 days   
6            7.519750  ...             128 days               9 days   
7            1.477520  ...              80 days              13 days   
8           12.672906  ...             126 days              78 days   
9           12.024903  ...              80 days              29 days   
10           7.004963  ...             196 days              42 days   
11          12.249207  ...             288 days              32 days   

    Profit Factor  Expectancy [%]       SQN  Kelly Criterion   _strategy  \
0        1.111937        0.250118  0.050265         0.007721  MyStrategy   
1        1.470296        1.187091  0.241894         0.070898  MyStrategy   
2        0.009044       -6.907929 -1.182126       -44.721951  MyStrategy   
3        1.565348        1.273079  0.613458         0.102120  MyStrategy   
4             NaN             NaN       NaN              NaN  MyStrategy   
5        1.572596        0.876759  0.451788         0.094363  MyStrategy   
6        1.485613        0.445068  0.771377         0.166333  MyStrategy   
7        0.207575       -1.945603 -2.163973        -1.543690  MyStrategy   
8        0.283372       -2.177661 -0.654040        -0.948784  MyStrategy   
9        4.630598        3.131993  1.596817         0.529359  MyStrategy   
10       1.657359        1.512648  0.569655         0.125697  MyStrategy   
11       1.097800        0.228987 -0.018232        -0.005564  MyStrategy   

                                        _equity_curve  \
0                     Equity  DrawdownPct Drawdown...   
1               

# Grid Search Optimization

In [149]:
param_grids = get_param_grids()
print("Working on optimizing with GridSearchCV")
best_models = grid_optimize_model(classifier,X_train_scaled, y_train,param_grids=param_grids)
results,y_pred_dict = train_model(classifiers=best_models, X_train_scaled=X_train_scaled, X_test_scaled=X_test_scaled,y_train=y_train,y_test=y_test)


Working on optimizing with GridSearchCV
Optimizing Logistic Regression...


c:\Users\sachi\Documents\Researchcode\research\lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(


Best parameters for Logistic Regression: {'C': 10, 'penalty': 'l1', 'solver': 'saga'}
Optimizing Random Forest...
Best parameters for Random Forest: {'max_depth': None, 'max_features': 'log2', 'min_samples_split': 2, 'n_estimators': 50}
Optimizing XGBoost...
Optimizing SVM...
Best parameters for SVM: {'C': 10, 'gamma': 'scale', 'kernel': 'linear'}
Optimizing Naive Bayes...
Best parameters for Naive Bayes: {'alpha': 0.1}
Optimizing Gradient Boosting...
Best parameters for Gradient Boosting: {'learning_rate': 0.1, 'max_depth': 5, 'min_samples_split': 2, 'n_estimators': 200}
Optimizing K-Nearest Neighbors...
Best parameters for K-Nearest Neighbors: {'algorithm': 'auto', 'n_neighbors': 7, 'p': 2, 'weights': 'uniform'}
Optimizing Decision Tree...
Best parameters for Decision Tree: {'criterion': 'entropy', 'max_depth': None, 'max_features': 'sqrt', 'min_samples_split': 2}
Optimizing AdaBoost...
Best parameters for AdaBoost: {'learning_rate': 0.1, 'n_estimators': 50}
Optimizing SGD Classifier

c:\Users\sachi\Documents\Researchcode\research\lib\site-packages\sklearn\model_selection\_validation.py:528: FitFailedWarning: 
60 fits failed out of a total of 120.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
60 fits failed with the following error:
Traceback (most recent call last):
  File "c:\Users\sachi\Documents\Researchcode\research\lib\site-packages\sklearn\model_selection\_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "c:\Users\sachi\Documents\Researchcode\research\lib\site-packages\sklearn\base.py", line 1389, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "c:\Users\sachi\Documents\Researchcode\research\lib\site-packages\sklearn\linear_model\_stochas

Best parameters for SGD Classifier: {'alpha': 0.001, 'learning_rate': 'optimal', 'loss': 'log_loss', 'penalty': 'l1'}
Optimizing MLP...
Best parameters for MLP: {'activation': 'tanh', 'alpha': 0.001, 'hidden_layer_sizes': (100,), 'learning_rate_init': 0.001, 'solver': 'adam'}
Optimizing LGBMClassifier...
[LightGBM] [Info] Number of positive: 1098, number of negative: 647
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.001992 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 16830
[LightGBM] [Info] Number of data points in the train set: 1745, number of used features: 66
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.629226 -> initscore=0.528899
[LightGBM] [Info] Start training from score 0.528899
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive ga

c:\Users\sachi\Documents\Researchcode\research\lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(



Logistic Regression Performance:
Accuracy: 0.8892
Confusion Matrix:
[[312  43]
 [ 40 354]]
              precision    recall  f1-score   support

           0       0.89      0.88      0.88       355
           1       0.89      0.90      0.90       394

    accuracy                           0.89       749
   macro avg       0.89      0.89      0.89       749
weighted avg       0.89      0.89      0.89       749


Random Forest Performance:
Accuracy: 0.6021
Confusion Matrix:
[[297  58]
 [240 154]]
              precision    recall  f1-score   support

           0       0.55      0.84      0.67       355
           1       0.73      0.39      0.51       394

    accuracy                           0.60       749
   macro avg       0.64      0.61      0.59       749
weighted avg       0.64      0.60      0.58       749


XGBoost Performance:
Accuracy: 0.5394
Confusion Matrix:
[[ 10 345]
 [  0 394]]
              precision    recall  f1-score   support

           0       1.00      0.03

c:\Users\sachi\Documents\Researchcode\research\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\sachi\Documents\Researchcode\research\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\sachi\Documents\Researchcode\research\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capita


Gradient Boosting Performance:
Accuracy: 0.6569
Confusion Matrix:
[[155 200]
 [ 57 337]]
              precision    recall  f1-score   support

           0       0.73      0.44      0.55       355
           1       0.63      0.86      0.72       394

    accuracy                           0.66       749
   macro avg       0.68      0.65      0.64       749
weighted avg       0.68      0.66      0.64       749


K-Nearest Neighbors Performance:
Accuracy: 0.6395
Confusion Matrix:
[[221 134]
 [136 258]]
              precision    recall  f1-score   support

           0       0.62      0.62      0.62       355
           1       0.66      0.65      0.66       394

    accuracy                           0.64       749
   macro avg       0.64      0.64      0.64       749
weighted avg       0.64      0.64      0.64       749


Decision Tree Performance:
Accuracy: 0.6529
Confusion Matrix:
[[119 236]
 [ 24 370]]
              precision    recall  f1-score   support

           0       0.83

c:\Users\sachi\Documents\Researchcode\research\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\sachi\Documents\Researchcode\research\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\sachi\Documents\Researchcode\research\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capita


AdaBoost Performance:
Accuracy: 0.5260
Confusion Matrix:
[[  0 355]
 [  0 394]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00       355
           1       0.53      1.00      0.69       394

    accuracy                           0.53       749
   macro avg       0.26      0.50      0.34       749
weighted avg       0.28      0.53      0.36       749


SGD Classifier Performance:
Accuracy: 0.8825
Confusion Matrix:
[[315  40]
 [ 48 346]]
              precision    recall  f1-score   support

           0       0.87      0.89      0.88       355
           1       0.90      0.88      0.89       394

    accuracy                           0.88       749
   macro avg       0.88      0.88      0.88       749
weighted avg       0.88      0.88      0.88       749


MLP Performance:
Accuracy: 0.8411
Confusion Matrix:
[[272  83]
 [ 36 358]]
              precision    recall  f1-score   support

           0       0.88      0.77      0.82    

c:\Users\sachi\Documents\Researchcode\research\lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(


In [150]:
results

Model  Accuracy          Confusion Matrix
0   Logistic Regression  0.889186    [[312, 43], [40, 354]]
1         Random Forest  0.602136   [[297, 58], [240, 154]]
2               XGBoost  0.539386     [[10, 345], [0, 394]]
3                   SVM  0.886515    [[319, 36], [49, 345]]
4           Naive Bayes  0.526035      [[0, 355], [0, 394]]
5     Gradient Boosting  0.656876   [[155, 200], [57, 337]]
6   K-Nearest Neighbors  0.639519  [[221, 134], [136, 258]]
7         Decision Tree  0.652870   [[119, 236], [24, 370]]
8              AdaBoost  0.526035      [[0, 355], [0, 394]]
9        SGD Classifier  0.882510    [[315, 40], [48, 346]]
10                  MLP  0.841121    [[272, 83], [36, 358]]
11       LGBMClassifier  0.636849     [[87, 268], [4, 390]]

In [151]:
stats_l=[]
bt_collection = {}
for name,y_pred in y_pred_dict.items():
    print(f"Backtesting for {name}")
    stats,bt = backtest(y_pred,X_test)
    bt_collection[name] = bt
    stats['Algorithm'] = name
    stats_l.append(stats)

grid_df = pd.DataFrame(stats_l)

Backtesting for Logistic Regression
<class 'numpy.ndarray'>


Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 1, Position: <Position: 0 (0 trades)>
Executing Buy Order
Signal: 1, Position: <Position: 58 (1 trades)>
Signal: 1, Position: <Position: 58 (1 trades)>
Signal: 1, Position: <Position: 58 (1 trades)>
Signal: 1, Position: <Position: 58 (1 trades)>
Signal: 1, Position: <Position: 58 (1 trades)>
Signal: 1, Position: <Position: 58 (1 trades)>
Signal: 1, Position: <Position: 58 (1 trades)>
Signal: 1, Position: <Position: 58 (1 trades)>
Signal

Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 1, Position: <Position: 0 (0 trades)>
Executing Buy Order
Signal: 1, Position: <Position: 57 (1 trades)>
Signal: 1, Position: <Position: 57 (1 trades)>
Signal: 1, P

Signal: 1, Position: <Position: 0 (0 trades)>
Executing Buy Order
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 tra

<class 'numpy.ndarray'>


Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 1, Position: <Position: 0 (0 trades)>
Executing Buy Order
Signal: 1, Position: <Position: 58 (1 trades)>
Signal: 1, Position: <Position: 58 (1 trades)>
Signal: 1, Position: <Position: 58 (1 trades)>
Signal: 1, Position: <Position: 58 (1 trades)>
Signal: 1, Position: <Position: 58 (1 trades)>
Signal: 1, Position: <Position: 58 (1 trades)>
Signal: 1, Position: <Position: 58 (1 trades)>
Signal: 1, Position: <Position: 58 (1 trades)>
Signal

Signal: 1, Position: <Position: 0 (0 trades)>
Executing Buy Order
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 tra

Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 1, Position: <Position: 0 (0 trades)>
Executing Buy Order
Signal: 1, Pos

Backtesting for K-Nearest Neighbors
<class 'numpy.ndarray'>


Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 1, Position: <Position: 0 (0 trades)>
Executing Buy Order
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 0, Position: <Position: 62 (1 trades)>
Closing Position
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 1, Position: <Position: 0 (0 trades)>
Executing Buy Order
Signal: 0, Position: <Position: 57 (1 trades)>
Closing Position
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Sig

Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 1, Position: <Position: 0 (0 trades)>
Executing Buy Order
Signal: 1, Position: <Position: 59 (1 trades)>
Signal: 1, Position: <Position: 59 (1 trades)>
Signal: 1, Position: <Position: 59 (1 trades)>
Signal: 1, Position: <Position: 59 (1 trades)>
Signal: 1, Position: <Position: 59 (1 trades)>
Signal: 1, Position: <Position: 59 (1 trades)>
Signal: 1, Position: <Position: 59 (1 trades)>
Signal: 1, Position: <Position: 59 (1 trades)>
Signal: 1, Position: <Position: 59 (1 trades)>
Signa

Signal: 1, Position: <Position: 0 (0 trades)>
Executing Buy Order
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 tra

Backtesting for SGD Classifier
<class 'numpy.ndarray'>


Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 1, Position: <Position: 0 (0 trades)>
Executing Buy Order
Signal: 1, Position: <Position: 58 (1 trades)>
Signal: 1, Position: <Position: 58 (1 trades)>
Signal: 1, Position: <Position: 58 (1 trades)>
Signal: 1, Position: <Position: 58 (1 trades)>
Signal: 1, Position: <Position: 58 (1 trades)>
Signal: 1, Position: <Position: 58 (1 trades)>
Signal: 1, Position: <Position: 58 (1 trades)>
Signal: 1, Position: <Position: 58 (1 trades)>
Signal

Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 1, Position: <Position: 0 (0 trades)>
Executing Buy Order
Signal: 1, Position: <Position: 57 (1 trades)>
Signal: 1, Position: <Position: 57 (1 trades)>
Signal: 1, Position: <Position: 57 (1 trades)>
Signal: 1, Position: <Position: 57 (1 trades)>
Signal: 1, Position: <Position: 57 (1 trades)>
Signal: 1, Position: <Position: 57 (1 trades)>
Signal: 1, Position: <Position: 57 (1 trades)>
Signal:

Signal: 1, Position: <Position: 0 (0 trades)>
Executing Buy Order
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 0, Position: <Position: 62 (1 trades)>
Closing Position
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 1, Position: <Position: 0 (0 trades)>
Executing Buy Order
Signal: 1, Position: <Position: 66 (1 trades)>
Signal: 1, Position: <Position: 66 (1 trades)>
Signal: 1, Position: <Position: 66 (1 trades)>
Signal: 1, Position: <Position: 66 (1 trades)>
Signal: 1, Position: <Position: 66 (1 trades)>
Signal: 1, Position: <Position: 66 (1 trades)>
Signal: 1, Position: <Position: 66 (1 trades)>
Signal: 1, Position: <Position: 66 (1 trades)>
Signal: 1, Position: <Position: 66 (1 trades)>
Signal: 1, Position: <Position: 66 (1 trades)>
Signal: 1, Position: <Position: 66 (1 trades)>
Signal: 1, Position: <Position: 66 (1 trades)>
Signal: 1, Position: <Position: 66 (1 trades)>
Signal: 1, Position: <Position: 66 (1 trades)>
Signal: 1, Position: <Position: 66 (1 trades)>
Signal

In [153]:
results

Model  Accuracy          Confusion Matrix
0   Logistic Regression  0.889186    [[312, 43], [40, 354]]
1         Random Forest  0.602136   [[297, 58], [240, 154]]
2               XGBoost  0.539386     [[10, 345], [0, 394]]
3                   SVM  0.886515    [[319, 36], [49, 345]]
4           Naive Bayes  0.526035      [[0, 355], [0, 394]]
5     Gradient Boosting  0.656876   [[155, 200], [57, 337]]
6   K-Nearest Neighbors  0.639519  [[221, 134], [136, 258]]
7         Decision Tree  0.652870   [[119, 236], [24, 370]]
8              AdaBoost  0.526035      [[0, 355], [0, 394]]
9        SGD Classifier  0.882510    [[315, 40], [48, 346]]
10                  MLP  0.841121    [[272, 83], [36, 358]]
11       LGBMClassifier  0.636849     [[87, 268], [4, 390]]

In [152]:
grid_df

Start        End  Duration  Exposure Time [%]  Equity Final [$]  \
0  2022-03-04 2025-02-27 1091 days          54.873164       9565.934383   
1  2022-03-04 2025-02-27 1091 days          29.372497      12265.790291   
2  2022-03-04 2025-02-27 1091 days          27.636849      14093.888193   
3  2022-03-04 2025-02-27 1091 days          52.336449      11979.267743   
4  2022-03-04 2025-02-27 1091 days           0.000000      14863.790367   
5  2022-03-04 2025-02-27 1091 days          48.865154      12954.456649   
6  2022-03-04 2025-02-27 1091 days          59.946595       9162.904819   
7  2022-03-04 2025-02-27 1091 days          54.739653      16187.187324   
8  2022-03-04 2025-02-27 1091 days           0.000000      14863.790367   
9  2022-03-04 2025-02-27 1091 days          53.004005      10951.024042   
10 2022-03-04 2025-02-27 1091 days          58.878505      11133.422678   
11 2022-03-04 2025-02-27 1091 days          61.682243      14097.946560   

    Equity Peak [$]  Commissions [$]  Return [%]  Buy & Hold Return [%]  \
0      12249.298394        94.914136   -4.340656              45.431149   
1      12265.790291        32.920402   22.657903              45.431149   
2      15375.367365         9.941782   40.938882              45.431149   
3      13701.264070        90.707834   19.792677              45.431149   
4      16210.429497              NaN   48.637904              45.431149   
5      14127.335891        68.504886   29.544566              45.431149   
6      11450.509530       210.584714   -8.370952              45.431149   
7      17664.146370        71.987292   61.871873              45.431149   
8      16210.429497              NaN   48.637904              45.431149   
9      12223.702886        84.756413    9.510240              45.431149   
10     13096.884430        60.366494   11.334227              45.431149   
11     15379.425732        77.401360   40.979466              45.431149   

    Return (Ann.) [%]  ...  Max. Trade Duration  Avg. Trade Duration  \
0           -1.481961  ...             145 days              24 days   
1            7.112829  ...             169 days              39 days   
2           12.238334  ...             190 days              98 days   
3            6.264390  ...             144 days              26 days   
4           14.264876  ...                  NaT                  NaT   
5            9.099631  ...             243 days              29 days   
6           -2.898461  ...              94 days              11 days   
7           17.591362  ...             172 days              36 days   
8           14.264876  ...                  NaT                  NaT   
9            3.103757  ...             143 days              27 days   
10           3.678370  ...             154 days              42 days   
11          12.249207  ...             288 days              32 days   

    Profit Factor  Expectancy [%]       SQN  Kelly Criterion   _strategy  \
0        1.068750        0.176051 -0.049592        -0.007275  MyStrategy   
1        2.558048        3.678902  0.576548         0.281301  MyStrategy   
2        0.009044       -6.907929 -1.182126       -44.721951  MyStrategy   
3        1.565348        1.273079  0.613458         0.102120  MyStrategy   
4             NaN             NaN       NaN              NaN  MyStrategy   
5        1.317216        0.583549  0.125785         0.064596  MyStrategy   
6        0.971335       -0.036693 -0.221261        -0.045724  MyStrategy   
7        1.777257        1.181929  0.546732         0.161485  MyStrategy   
8             NaN             NaN       NaN              NaN  MyStrategy   
9        1.362886        0.783374  0.375783         0.069271  MyStrategy   
10       1.349894        0.909912  0.326758         0.077391  MyStrategy   
11       1.097800        0.228987 -0.018232        -0.005564  MyStrategy   

                                        _equity_curve  \
0                     Equity  DrawdownPct Drawdown...   
1               

In [154]:
print("Working on optimizing with RandomSearchCV")
random_best_models = random_optimize_model(classifier,X_train_scaled, y_train,param_grids=param_grids)
results,y_pred_dict = train_model(classifiers=random_best_models, X_train_scaled=X_train_scaled, X_test_scaled=X_test_scaled,y_train=y_train,y_test=y_test)


Working on optimizing with RandomSearchCV
Optimizing Logistic Regression...
Fitting 5 folds for each of 10 candidates, totalling 50 fits


c:\Users\sachi\Documents\Researchcode\research\lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(


Best parameters for Logistic Regression: {'solver': 'saga', 'penalty': 'l1', 'C': 10}
Optimizing Random Forest...
Fitting 5 folds for each of 10 candidates, totalling 50 fits
Best parameters for Random Forest: {'n_estimators': 100, 'min_samples_split': 2, 'max_features': 'sqrt', 'max_depth': 10}
Optimizing XGBoost...
No hyperparameters to tune for XGBoost
Optimizing SVM...
Fitting 5 folds for each of 10 candidates, totalling 50 fits
Best parameters for SVM: {'kernel': 'linear', 'gamma': 'auto', 'C': 10}
Optimizing Naive Bayes...
Fitting 5 folds for each of 3 candidates, totalling 15 fits
Best parameters for Naive Bayes: {'alpha': 0.1}
Optimizing Gradient Boosting...
Fitting 5 folds for each of 10 candidates, totalling 50 fits


c:\Users\sachi\Documents\Researchcode\research\lib\site-packages\sklearn\model_selection\_search.py:317: UserWarning: The total space of parameters 3 is smaller than n_iter=10. Running 3 iterations. For exhaustive searches, use GridSearchCV.
  warnings.warn(


Best parameters for Gradient Boosting: {'n_estimators': 200, 'min_samples_split': 10, 'max_depth': 5, 'learning_rate': 0.1}
Optimizing K-Nearest Neighbors...
Fitting 5 folds for each of 10 candidates, totalling 50 fits
Best parameters for K-Nearest Neighbors: {'weights': 'distance', 'p': 2, 'n_neighbors': 7, 'algorithm': 'kd_tree'}
Optimizing Decision Tree...
Fitting 5 folds for each of 10 candidates, totalling 50 fits
Best parameters for Decision Tree: {'min_samples_split': 2, 'max_features': 'sqrt', 'max_depth': 10, 'criterion': 'entropy'}
Optimizing AdaBoost...
Fitting 5 folds for each of 6 candidates, totalling 30 fits


c:\Users\sachi\Documents\Researchcode\research\lib\site-packages\sklearn\model_selection\_search.py:317: UserWarning: The total space of parameters 6 is smaller than n_iter=10. Running 6 iterations. For exhaustive searches, use GridSearchCV.
  warnings.warn(


Best parameters for AdaBoost: {'n_estimators': 50, 'learning_rate': 0.1}
Optimizing SGD Classifier...
Fitting 5 folds for each of 10 candidates, totalling 50 fits


c:\Users\sachi\Documents\Researchcode\research\lib\site-packages\sklearn\model_selection\_validation.py:528: FitFailedWarning: 
25 fits failed out of a total of 50.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
25 fits failed with the following error:
Traceback (most recent call last):
  File "c:\Users\sachi\Documents\Researchcode\research\lib\site-packages\sklearn\model_selection\_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "c:\Users\sachi\Documents\Researchcode\research\lib\site-packages\sklearn\base.py", line 1389, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "c:\Users\sachi\Documents\Researchcode\research\lib\site-packages\sklearn\linear_model\_stochast

Best parameters for SGD Classifier: {'penalty': 'l2', 'loss': 'log_loss', 'learning_rate': 'optimal', 'alpha': 0.001}
Optimizing MLP...
Fitting 5 folds for each of 10 candidates, totalling 50 fits
Best parameters for MLP: {'solver': 'sgd', 'learning_rate_init': 0.001, 'hidden_layer_sizes': (50, 50), 'alpha': 0.001, 'activation': 'tanh'}
Optimizing LGBMClassifier...
[LightGBM] [Info] Number of positive: 1098, number of negative: 647
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.001761 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 16830
[LightGBM] [Info] Number of data points in the train set: 1745, number of used features: 66
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.629226 -> initscore=0.528899
[LightGBM] [Info] Start training from score 0.528899
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain

c:\Users\sachi\Documents\Researchcode\research\lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(



Logistic Regression Performance:
Accuracy: 0.8892
Confusion Matrix:
[[312  43]
 [ 40 354]]
              precision    recall  f1-score   support

           0       0.89      0.88      0.88       355
           1       0.89      0.90      0.90       394

    accuracy                           0.89       749
   macro avg       0.89      0.89      0.89       749
weighted avg       0.89      0.89      0.89       749


Random Forest Performance:
Accuracy: 0.6368
Confusion Matrix:
[[251 104]
 [168 226]]
              precision    recall  f1-score   support

           0       0.60      0.71      0.65       355
           1       0.68      0.57      0.62       394

    accuracy                           0.64       749
   macro avg       0.64      0.64      0.64       749
weighted avg       0.64      0.64      0.64       749


XGBoost Performance:
Accuracy: 0.5394
Confusion Matrix:
[[ 10 345]
 [  0 394]]
              precision    recall  f1-score   support

           0       1.00      0.03

c:\Users\sachi\Documents\Researchcode\research\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\sachi\Documents\Researchcode\research\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\sachi\Documents\Researchcode\research\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capita


Gradient Boosting Performance:
Accuracy: 0.6155
Confusion Matrix:
[[297  58]
 [230 164]]
              precision    recall  f1-score   support

           0       0.56      0.84      0.67       355
           1       0.74      0.42      0.53       394

    accuracy                           0.62       749
   macro avg       0.65      0.63      0.60       749
weighted avg       0.66      0.62      0.60       749


K-Nearest Neighbors Performance:
Accuracy: 0.6395
Confusion Matrix:
[[221 134]
 [136 258]]
              precision    recall  f1-score   support

           0       0.62      0.62      0.62       355
           1       0.66      0.65      0.66       394

    accuracy                           0.64       749
   macro avg       0.64      0.64      0.64       749
weighted avg       0.64      0.64      0.64       749


Decision Tree Performance:
Accuracy: 0.6462
Confusion Matrix:
[[138 217]
 [ 48 346]]
              precision    recall  f1-score   support

           0       0.74

c:\Users\sachi\Documents\Researchcode\research\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\sachi\Documents\Researchcode\research\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\sachi\Documents\Researchcode\research\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capita


AdaBoost Performance:
Accuracy: 0.5260
Confusion Matrix:
[[  0 355]
 [  0 394]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00       355
           1       0.53      1.00      0.69       394

    accuracy                           0.53       749
   macro avg       0.26      0.50      0.34       749
weighted avg       0.28      0.53      0.36       749


SGD Classifier Performance:
Accuracy: 0.8825
Confusion Matrix:
[[317  38]
 [ 50 344]]
              precision    recall  f1-score   support

           0       0.86      0.89      0.88       355
           1       0.90      0.87      0.89       394

    accuracy                           0.88       749
   macro avg       0.88      0.88      0.88       749
weighted avg       0.88      0.88      0.88       749


MLP Performance:
Accuracy: 0.8371
Confusion Matrix:
[[256  99]
 [ 23 371]]
              precision    recall  f1-score   support

           0       0.92      0.72      0.81    

c:\Users\sachi\Documents\Researchcode\research\lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(


In [155]:
stats_l=[]
bt_collection = {}
for name,y_pred in y_pred_dict.items():
    print(f"Backtesting for {name}")
    stats,bt = backtest(y_pred,X_test)
    bt_collection[name] = bt
    stats['Algorithm'] = name
    stats_l.append(stats)

random_df = pd.DataFrame(stats_l)

Backtesting for Logistic Regression
<class 'numpy.ndarray'>


Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 1, Position: <Position: 0 (0 trades)>
Executing Buy Order
Signal: 1, Position: <Position: 58 (1 trades)>
Signal: 1, Position: <Position: 58 (1 trades)>
Signal: 1, Position: <Position: 58 (1 trades)>
Signal: 1, Position: <Position: 58 (1 trades)>
Signal: 1, Position: <Position: 58 (1 trades)>
Signal: 1, Position: <Position: 58 (1 trades)>
Signal: 1, Position: <Position: 58 (1 trades)>
Signal: 1, Position: <Position: 58 (1 trades)>
Signal

Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 1, Position: <Position: 0 (0 trades)>
Executing Buy Order
Signal: 1, Position: <Position: 58 (1 trades)>
Signal: 1, Position: <Position: 58 (1 trades)>
Signal: 1, Position: <Position: 58 (1 trades)>
Signal: 1, Position: <Position: 58 (1 trades)>
Signal: 1, Position: <Position: 58 (1 trades)>
Signal: 1, Position: <Position: 58 (1 trades)>
Signal: 1, Position: <Position: 58 (1 trades)>
Signal: 1, Position: <Position: 58 (1 trades)>
Signal

Signal: 1, Position: <Position: 0 (0 trades)>
Executing Buy Order
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 tra

Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 1, Position: <Position: 0 (0 trades)>
Executing Buy Order
Signal: 1, Position: <Position: 58 (1 trades)>
Signal: 1, Position: <Position: 58 (1 trades)>
Signal: 1, Position: <Position: 58 (1 trades)>
Signal: 1, Position: <Position: 58 (1 trades)>
Signal: 1, Position: <Position: 58 (1 trades)>
Signal: 1, Position: <Position: 58 (1 trades)>
Signal: 1, Position: <Position: 58 (1 trades)>
Signal: 1, Position: <Position: 58 (1 trades)>
Signal

Signal: 1, Position: <Position: 0 (0 trades)>
Executing Buy Order
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 tra

Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 1, Position: <Position: 0 (0 trades)>
Executing Buy Order
Signal: 1, Pos

Backtesting for K-Nearest Neighbors
<class 'numpy.ndarray'>


Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 1, Position: <Position: 0 (0 trades)>
Executing Buy Order
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 0, Position: <Position: 62 (1 trades)>
Closing Position
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 1, Position: <Position: 0 (0 trades)>
Executing Buy Order
Signal: 0, Position: <Position: 57 (1 trades)>
Closing Position
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Sig

Backtesting for Decision Tree
<class 'numpy.ndarray'>


Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 1, Position: <Position: 0 (0 trades)>
Executing Buy Order
Signal: 1, Position: <Position: 57 (1 trades)>
Signal: 1, Position: <Position: 57 (1 trades)>
Signal: 1, Position: <Position: 57 (1 trades)>
Signal: 1, Position: <Position: 57 (1 trades)>
Signal: 1, Position: <Position: 57 (1 trades)>
Signal: 1, Position: <Position: 57 (1 trades)>
Signal: 1, Position: <Position: 57 (1 trades)>
Signal:

Signal: 1, Position: <Position: 0 (0 trades)>
Executing Buy Order
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 1, Position: <Position: 62 (1 tra

Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 1, Position: <Position: 0 (0 trades)>
Executing Buy Order
Signal: 1, Position: <Position: 57 (1 trades)>
Signal: 1, Position: <Position: 57 (1 trades)>
Signal: 1, Position: <Position: 57 (1 trades)>
Signal: 1, Position: <Position: 57 (1 trades)>
Signal: 1, Position: <Position: 57 (1 trades)>
Signal: 1, Position: <Position: 57 (1 trades)>
Signal: 1, Position: <Position: 57 (1 trades)>
Signal:

Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 1, Position: <Position: 0 (0 trades)>
Executing Buy Order
Signal: 1, Position: <Position: 58 (1 trades)>
Signal: 1, Position: <Position: 58 (1 trades)>
Signal: 1, Position: <Position: 58 (1 trades)>
Signal: 1, Position: <Position: 58 (1 trades)>
Signal: 1, Position: <Position: 58 (1 trades)>
Signal: 1, Position: <Position: 58 (1 trades)>
Signal: 1, Position: <Position: 58 (1 trades)>
Signal: 1, Position: <Position: 58 (1 trades)>
Signal

Signal: 1, Position: <Position: 0 (0 trades)>
Executing Buy Order
Signal: 1, Position: <Position: 62 (1 trades)>
Signal: 0, Position: <Position: 62 (1 trades)>
Closing Position
Signal: 0, Position: <Position: 0 (0 trades)>
Signal: 1, Position: <Position: 0 (0 trades)>
Executing Buy Order
Signal: 1, Position: <Position: 66 (1 trades)>
Signal: 1, Position: <Position: 66 (1 trades)>
Signal: 1, Position: <Position: 66 (1 trades)>
Signal: 1, Position: <Position: 66 (1 trades)>
Signal: 1, Position: <Position: 66 (1 trades)>
Signal: 1, Position: <Position: 66 (1 trades)>
Signal: 1, Position: <Position: 66 (1 trades)>
Signal: 1, Position: <Position: 66 (1 trades)>
Signal: 1, Position: <Position: 66 (1 trades)>
Signal: 1, Position: <Position: 66 (1 trades)>
Signal: 1, Position: <Position: 66 (1 trades)>
Signal: 1, Position: <Position: 66 (1 trades)>
Signal: 1, Position: <Position: 66 (1 trades)>
Signal: 1, Position: <Position: 66 (1 trades)>
Signal: 1, Position: <Position: 66 (1 trades)>
Signal

In [156]:
results

Model  Accuracy          Confusion Matrix
0   Logistic Regression  0.889186    [[312, 43], [40, 354]]
1         Random Forest  0.636849  [[251, 104], [168, 226]]
2               XGBoost  0.539386     [[10, 345], [0, 394]]
3                   SVM  0.886515    [[319, 36], [49, 345]]
4           Naive Bayes  0.526035      [[0, 355], [0, 394]]
5     Gradient Boosting  0.615487   [[297, 58], [230, 164]]
6   K-Nearest Neighbors  0.639519  [[221, 134], [136, 258]]
7         Decision Tree  0.646195   [[138, 217], [48, 346]]
8              AdaBoost  0.526035      [[0, 355], [0, 394]]
9        SGD Classifier  0.882510    [[317, 38], [50, 344]]
10                  MLP  0.837116    [[256, 99], [23, 371]]
11       LGBMClassifier  0.636849     [[87, 268], [4, 390]]

In [157]:
random_df

Start        End  Duration  Exposure Time [%]  Equity Final [$]  \
0  2022-03-04 2025-02-27 1091 days          54.873164       9565.934383   
1  2022-03-04 2025-02-27 1091 days          48.064085      12747.759698   
2  2022-03-04 2025-02-27 1091 days          27.636849      14093.888193   
3  2022-03-04 2025-02-27 1091 days          52.336449      11979.267743   
4  2022-03-04 2025-02-27 1091 days           0.000000      14863.790367   
5  2022-03-04 2025-02-27 1091 days          31.909212      11371.619818   
6  2022-03-04 2025-02-27 1091 days          59.946595       9162.904819   
7  2022-03-04 2025-02-27 1091 days          50.734312      14244.672698   
8  2022-03-04 2025-02-27 1091 days           0.000000      14863.790367   
9  2022-03-04 2025-02-27 1091 days          52.469960       9809.245163   
10 2022-03-04 2025-02-27 1091 days          61.815754      12797.282562   
11 2022-03-04 2025-02-27 1091 days          61.682243      14097.946560   

    Equity Peak [$]  Commissions [$]  Return [%]  Buy & Hold Return [%]  \
0      12249.298394        94.914136   -4.340656              45.431149   
1      12747.759698       122.960608   27.477597              45.431149   
2      15375.367365         9.941782   40.938882              45.431149   
3      13701.264070        90.707834   19.792677              45.431149   
4      16210.429497              NaN   48.637904              45.431149   
5      11451.797261        61.778512   13.716198              45.431149   
6      11450.509530       210.584714   -8.370952              45.431149   
7      15547.871855       103.128701   42.446727              45.431149   
8      16210.429497              NaN   48.637904              45.431149   
9      12534.503524        79.393966   -1.907548              45.431149   
10     14185.536912        59.065298   27.972826              45.431149   
11     15379.425732        77.401360   40.979466              45.431149   

    Return (Ann.) [%]  ...  Max. Trade Duration  Avg. Trade Duration  \
0           -1.481961  ...             145 days              24 days   
1            8.510828  ...             189 days              16 days   
2           12.238334  ...             190 days              98 days   
3            6.264390  ...             144 days              26 days   
4           14.264876  ...                  NaT                  NaT   
5            4.419437  ...              92 days              20 days   
6           -2.898461  ...              94 days              11 days   
7           12.640912  ...             126 days              23 days   
8           14.264876  ...                  NaT                  NaT   
9           -0.645897  ...             145 days              28 days   
10           8.652474  ...             158 days              47 days   
11          12.249207  ...             288 days              32 days   

    Profit Factor  Expectancy [%]       SQN  Kelly Criterion   _strategy  \
0        1.068750        0.176051 -0.049592        -0.007275  MyStrategy   
1        1.791870        1.200247  0.727540         0.200407  MyStrategy   
2        0.009044       -6.907929 -1.182126       -44.721951  MyStrategy   
3        1.565348        1.273079  0.613458         0.102120  MyStrategy   
4             NaN             NaN       NaN              NaN  MyStrategy   
5        1.471315        1.134794  0.469292         0.114933  MyStrategy   
6        0.971335       -0.036693 -0.221261        -0.045724  MyStrategy   
7        1.587644        0.634119  0.557967         0.151498  MyStrategy   
8             NaN             NaN       NaN              NaN  MyStrategy   
9        1.151677        0.379228  0.048408         0.011137  MyStrategy   
10       2.152371        2.124138  1.022938         0.219975  MyStrategy   
11       1.097800        0.228987 -0.018232        -0.005564  MyStrategy   

                                        _equity_curve  \
0                     Equity  DrawdownPct Drawdown...   
1               

In [ ]:
print(results)

In [160]:
model = best_models['Decision Tree']

In [162]:
model.fit(X_train_scaled,y_train)

DecisionTreeClassifier(criterion='entropy', max_features='sqrt')

In [164]:
y_pred = model.predict(X_test_scaled)

In [165]:
from sklearn.metrics import confusion_matrix,classification_report

In [166]:
confusion_matrix(y_test,y_pred)

array([[212, 143],
       [197, 197]])

In [169]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.52      0.60      0.55       355
           1       0.58      0.50      0.54       394

    accuracy                           0.55       749
   macro avg       0.55      0.55      0.55       749
weighted avg       0.55      0.55      0.55       749



In [170]:
import os

In [ ]:
os.getcwd()

'c:\\Users\\sachi\\Documents\\Researchcode\\notebook'

In [178]:
dir = r'C:\Users\sachi\Documents\Researchcode\sentiment'

In [181]:
for paths in os.listdir(dir):
    path = os.path.join(dir,paths)

In [188]:
saving_dir = os.path.join(dir, 'optimized')

In [189]:
os.makedirs(saving_dir,exist_ok=True)

In [190]:
random_df.to_csv(f'{saving_dir}/aapl.csv')